name: Build and Publish  Docker Image to DockerHub


on:
  workflow_dispatch:

  push:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'decision records/**'
      - 'demoreel/**'
      - 'prerequisites/**'
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    - name: 'Get package version'
      run: |
        echo "PKG_VERSION=$(jq -r ".version" packages/sfpowerscripts-cli/package.json)" >> $GITHUB_ENV



    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          file: docker/Dockerfile
          push: true
          tags: dxatscale/sfpowerscripts:${{ env. PKG_VERSION}}
          buildArgs:| 
                  SFPOWERCRIPTS_VERSION=${{ env. PKG_VERSION}}
