# This pipeline builds the sfpowerscripts plugin

name: 'Release'

on:
   push:
    branches:
      - develop
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - 'decision records/**'
      - 'demoreel/**'
      - 'prerequisites/**'

   workflow_dispatch:

jobs:
#Merge to Develop, Deploy Alpha builds    
  alpha:
    name: 'build alpha packages'
    uses: ./.github/workflows/buildPackages.yml
    with:
      version: 'alpha'
      publish: true
      environment: alpha
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    if: ${{ github.ref == 'refs/heads/develop' }}
    concurrency:
      group: alpha

  alpha-docker:
    name: 'build alpha docker image'
    uses: ./.github/workflows/buildDocker.yml
    with:
      version: 'alpha'
      environment: 'alpha-docker'
    secrets:
      gh-token: ${{ secrets.CONTAINER_PAT_TOKEN }}
    if: ${{ always() }}
    concurrency:
      group: alpha-docker
    needs: [alpha]

# Hotfix stage
  hotfix:
    name: 'build hotfix packages'
    uses: ./.github/workflows/buildPackages.yml
    with:
      version: 'hotfix'
      publish: true
      environment: hotfix
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency:
     group: hotfix

  hotfix-docker:
    name: 'build hotfix docker'
    uses: ./.github/workflows/buildDocker.yml
    with:
      version: 'hotfix'
      environment: 'hotfix-docker'
    secrets:
      gh-token: ${{ secrets.CONTAINER_PAT_TOKEN }}
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency:
      group: hotfix-docker
    needs: [hotfix]

  sfpowerscripts-beta:
    name: 'sfpowerscripts Beta'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/sfpowerscripts-cli/package.json'
      environment: sfpowerscripts-beta
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: [alpha, alpha-docker]
  
  beta-docker:
    name: 'build beta docker'
    uses: ./.github/workflows/buildDocker.yml
    with:
      version: 'beta'
      environment: 'beta-docker'
    secrets:
      gh-token: ${{ secrets.CONTAINER_PAT_TOKEN }}
    if: ${{ github.ref == 'refs/heads/develop' }}
    concurrency:
      group: beta-docker
    needs: [alpha-docker] 

  sfpowerscripts-prod:
    name: 'sfpowerscripts Prod'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/sfpowerscripts-cli/package.json'
      environment: sfpowerscripts-prod
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    if: ${{ always() && (github.ref == 'refs/heads/main' && needs.hotfix.result == 'success' || github.ref == 'refs/heads/develop' && needs.sfpowerscripts-beta.result == 'success')  }}
    needs: [sfpowerscripts-beta, hotfix]

  prod-docker:
    name: 'build prod docker'
    uses: ./.github/workflows/buildDocker.yml
    with:
      version: 'latest'
      environment: 'prod-docker'
    secrets:
      gh-token: ${{ secrets.CONTAINER_PAT_TOKEN }}
    if: ${{ always() && (github.ref == 'refs/heads/main' && needs.hotfix.result == 'success' || github.ref == 'refs/heads/develop' && needs.sfpowerscripts-beta.result == 'success')  }}
    concurrency:
      group: prod-docker
    needs: [hotfix-docker, beta-docker]

  core-beta:
    name: 'core beta'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/core/package.json'
      environment: core-beta
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha

  core-prod:
    name: 'core prod'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/core/package.json'
      environment: core-prod
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    if: ${{ always() && (github.ref == 'refs/heads/main' && needs.hotfix.result == 'success' || github.ref == 'refs/heads/develop' && needs.core-beta.result == 'success')  }}
    needs: [core-beta, hotfix]

  sfp-beta:
    name: 'sfp-cli beta'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'beta'
      pathToPackageJson: 'packages/sfp-cli/package.json'
      environment: sfp-beta
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: alpha

  sfp-prod:
    name: 'sfp-cli prod'
    uses: ./.github/workflows/promotePackage.yml
    with:
      version: 'latest'
      pathToPackageJson: 'packages/sfp-cli/package.json'
      environment: sfp-prod
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
    if: ${{ always() && (github.ref == 'refs/heads/main' && needs.hotfix.result == 'success' || github.ref == 'refs/heads/develop' && needs.sfp-beta.result == 'success')  }}
    needs: [sfp-beta, hotfix]
